### ISSUE TITLE
Add retry logic.

### ISSUE THREAD

**Issue by ashishth09** [IBM-Cloud/bluemix-go#1]
The API sometimes timeouts due to different network errors. On some occasions we can  simply retry to see if things can work again. We had the implementation in the rest client. But we are re-using the code from the bluemix-cli-sdk now which doesn't have it. 

We need to see the appropriate place to put the logic to be re-usable across the SDK.

**Comment by Praveengostu** [comment]
Evaluted some of the opensource retryable http. One of which we can use could be https://github.com/PuerkitoBio/rehttp

**Comment by Ravenwater** [comment]
What is the status of this request?

**Comment by hkantare** [comment]
We have support for retry now in IBM Cloud sdk

**Comment by alsm** [comment]
Closing this as the feature has been added
