### ISSUE TITLE
Some packages are not displayed in godoc

### ISSUE THREAD

**Issue by huikang** [IBM-Cloud/bluemix-go#73]
I noticed that the bluemix-go has been moved from IBM-Bluemix namespace to IBM-Cloud. Will this affect the godoc reference page [1]? I think several packages are missing such as mccpv2, containers, etc; the refresh link does not help either.

[1] https://godoc.org/github.com/IBM-Cloud/bluemix-go

**Comment by ashishth09** [comment]
If some doc is not listing you could access it manually and then it will show up in the main page. Refresh won't help. That is the case with packages which are not top level

To list mccpv2 package you should access
https://godoc.org/github.com/IBM-Cloud/bluemix-go/api/mccp/mccpv2

and then it shows up in the https://godoc.org/github.com/IBM-Cloud/bluemix-go

**Comment by huikang** [comment]
Thanks for the explanation.
