### ISSUE TITLE
Update the import path in the examples

### ISSUE THREAD

**Issue by huikang** [IBM-Cloud/bluemix-go#74]
Some examples still use the old path [1]: ``github.com/IBM-Bluemix/bluemix-go``.... Although this does not produce any error, will it be better to update the path to ``github.com/IBM-Cloud/...?

[1] https://github.com/IBM-Cloud/bluemix-go/blob/master/examples/container/download_config/main.go#L9-L13

**Comment by alsm** [comment]
All examples have the correct path now
