### ISSUE TITLE
Request failed with status code: 400, BXNIM0106E: Validation of property 'response_type' with value '[uaa, cloud_iam]' failed. Valid values: 'cloud_iam'

### ISSUE THREAD

**Issue by renier** [IBM-Cloud/bluemix-go#87]
Getting the following error when invoking `iamauth.AuthenticateAPIKey(apikey)`:
```
Request failed with status code: 400, BXNIM0106E:
Validation of property 'response_type' with value '[uaa, cloud_iam]' failed.
Valid values: 'cloud_iam'
```

Which points to the following line in `authentication/iam.go`:
```go
Field("response_type", "cloud_iam,uaa").
```

If I set the `response_type` to just `cloud_iam`, as the error message above suggests, the API returns successfully.

**Comment by sakshiag** [comment]
@renier: I tried invoking the function  tokenRefreher.AuthenticateAPIKey()
I am able to generate the tokens.

**Comment by renier** [comment]
@sakshiag It works for me now as well. Must have been a temporary problem.
