### ISSUE TITLE
Support cluster GetDataCenterVlans

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/bluemix-go#91]
Need to be able to list the vlans within a DC for provisioning a cluster.  

https://us-south.containers.bluemix.net/swagger-api/#!/properties/GetDatacenterVLANs

I have the code working for the support of this, please let me know how to contribute

**Comment by ashishth09** [comment]
Please raise a PR with accompanying unit tests and preferably adding an example in the examples folder.

**Comment by argeiger** [comment]
@ashishth09 added #92

**Comment by argeiger** [comment]
Closing as functionality has been added
